### ISSUE TITLE
St_AsMVT: Duplicated keys

### ISSUE THREAD

**Issue by Algunenano** [CartoDB/postgis#20]
Given the [NYC trees dataset](https://data.cityofnewyork.us/api/geospatial/pi5s-9p35?method=export&format=Original) and requesting the tile 0/0/0 with the following query:
```sql
SELECT ((
 SELECT ST_AsMVT(geom, 'layer0')
 FROM (
 SELECT
 ST_AsMVTGeom(
 the_geom_webmercator,
 CDB_XYZ_Extent(0,0,0),
 4096,
 1024,
 true
 ) as the_geom_webmercator
 , cartodb_id, tree_id, block_id, created_at, tree_dbh, stump_diam, curb_loc, status, health, spc_latin, spc_common, steward, guards, sidewalk, user_type, problems, root_stone, root_grate, root_other, trnk_wire, trnk_light, trnk_other, brnch_ligh, brnch_shoe, brnch_othe, address, zipcode, zip_city, cb_num, borocode, boroname, cncldist, st_assem, st_senate, nta, nta_name, boro_ct, state, latitude, longitude, x_sp, y_sp
 FROM (select * from benchmark_d8e8efa7f605fc5f0bc8c68907284f77db485ae4fc737f3230705) AS cdbq
 WHERE
 the_geom_webmercator &&
 ST_Expand(
 CDB_XYZ_Extent(0,0,0),
 CDB_XYZ_Resolution(0) * 64
 )
 ) AS geom
 )) AS st_asmvt
```

Returns the columns triplicated (126):
```
$ protoc --decode=vector_tile.Tile ./node_modules/mapnik-vector-tile/proto/vector_tile.proto < /tmp/postgis.mvt | grep keys | sort 
  keys: "address"
  keys: "address"
  keys: "address"
  keys: "block_id"
  keys: "block_id"
  keys: "block_id"
  keys: "borocode"
  keys: "borocode"
  keys: "borocode"
  keys: "boro_ct"
```

```
١(º_º)١┳━┳[raul node-mapnik]$ protoc --decode=vector_tile.Tile ./node_modules/mapnik-vector-tile/proto/vector_tile.proto < /tmp/postgis.mvt | grep keys | wc -l
126
١(º_º)١┳━┳[raul node-mapnik]$ protoc --decode=vector_tile.Tile ./node_modules/mapnik-vector-tile/proto/vector_tile.proto < /tmp/mapnik.mvt | grep keys | wc -l
42
```

In comparison the tile is 20% in comparison with Mapnik's:
```
-rw-r--r-- 1 raul raul 129M jul  2 17:36 /tmp/mapnik.mvt
-rw-r--r-- 1 raul raul 154M jul  2 17:37 /tmp/postgis.mvt
```

This seems to only happen with big tiles. For example it does not happen with the tile `11,602,769` (50k points) but it does happen with `0,0,0` (680k points).

Testing with Postgis trunk.

**Comment by pramsey** [comment]
Possible that the PostGIS MVT code is testing attribute name equality in building up hash tables by comparing pointer values, rather than string values? That's the only thing that leaps immediately into my mind.

**Comment by Algunenano** [comment]
I'm thinking that it could be either an overflow somewhere or the parallel gather not joining the existing columns properly. I still haven't investigated it.

**Comment by Algunenano** [comment]
Here is the plan: Having 3 rows seems suspicious
```
-------------------------------------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=41449.85..41449.86 rows=1 width=32) (actual time=7374.895..7374.896 rows=1 loops=1)
   InitPlan 1 (returns $1)
     ->  Finalize Aggregate  (cost=41449.84..41449.85 rows=1 width=32) (actual time=7293.454..7293.454 rows=1 loops=1)
           ->  Gather  (cost=41449.62..41449.83 rows=2 width=32) (actual time=4820.967..4914.876 rows=3 loops=1)
                 Workers Planned: 2
                 Workers Launched: 2
                 ->  Partial Aggregate  (cost=40449.62..40449.63 rows=1 width=32) (actual time=4841.956..4841.956 rows=1 loops=3)
                       ->  Parallel Seq Scan on benchmark_d8e8efa7f605fc5f0bc8c68907284f77db485ae4fc737f3230705  (cost=0.00..39025.16 rows=
284892 width=340) (actual time=0.017..102.699 rows=227929 loops=3)
                             Filter: (the_geom_webmercator && '0103000020110F00000100000005000000DC183A68F4A97CC1DC183A68F4A97CC1DC183A68F4
A97CC1DC183A68F4A97C41DC183A68F4A97C41DC183A68F4A97C41DC183A68F4A97C41DC183A68F4A97CC1DC183A68F4A97CC1DC183A68F4A97CC1'::geometry)
 Planning Time: 0.860 ms
 Execution Time: 7521.889 ms
```

Maybe it joins the three intermediate outputs one after the other instead of merging them?

**Comment by pramsey** [comment]
Mmmmmm... yes, it's the parallel thing, I'm pretty sure in the parallel MVT code I don't bother to merge the dictionaries. I'm also pretty sure it doesn't matter...? I guess the issue is if you expect the dictionary to be single-valued, it'll break client expectations. What does the spec say?

**Comment by Algunenano** [comment]
As we talked yesterday the column duplication is due to how the combination of the results of the parallel workers is done. 

I've generated a smaller tile by tweaking the costs: ([a.mvt.zip](https://github.com/CartoDB/postgis/files/2158725/a.mvt.zip)):
- Reading the tile directly from protoc I see that it includes 2089 features.
- Using `node-mapnik` to read the data, no error are reported and it includes  2089 features too.

This is what the spec says about it:
```
Each element in the keys field of the layer is a string. The keys include all the keys of features used in the layer, and each key may be referenced by its positional index in this set of keys, with the first key having an index of 0. The set of keys SHOULD NOT contain two or more values which are byte-for-byte identical.
```

And, since wording is important (https://www.ietf.org/rfc/rfc2119.txt):
```
4. SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
   there may exist valid reasons in particular circumstances when the
   particular behavior is acceptable or even useful, but the full
   implications should be understood and the case carefully weighed
   before implementing any behavior described with this label.
```

So ideally we should avoid returning multiple keys with the same value and merge them instead, so any decoder can read them and the tiles are smaller.

Ey @davidmanzanares, to decide whether and when to tackle this it'd nice to know if CartoVL handles this without issues. Node-mapnik handles it correctly but I think you had a custom decoder. Could you please have a look? I can create an issue if you want

**Comment by davidmanzanares** [comment]
Hi @Algunenano, actually, we don't have our own decoder, although we manage the orientation issue. We manage that because the decoder we use (https://github.com/mapbox/vector-tile-js) doesn't manage it at all (it decodes the rings of the polygons, but it doesn't output the polygons, just the rings).

Because of that, I think that CARTO VL will work if, and only if, Mapbox GL works with those tiles.

If you send me one MVT tile (with only one is fine) I can check it easily.

**Comment by Algunenano** [comment]
There is one in my previous message (you'll need to unzip it). It corresponds to 13/2409/3081 (NYC) and it has 2089 features with 42 keys each.

**Comment by davidmanzanares** [comment]
Ops, I didn't see it, I'll test it

**Comment by davidmanzanares** [comment]
After a quick check, that tile doesn't work out of the box with CARTO VL, there is no error anywhere, but nothing (apart from the basemap) is shown. After some debugging I saw that this happens because all the points are outside the tile boundary (buffersize?), and we were clipping them. After disabling clipping the points are shown, and by debugging something more I think that it could work fine:

![seemsgood](https://user-images.githubusercontent.com/1692175/42216303-adba0f22-7ec1-11e8-89b7-9377f81a7e4e.png)


However, the last feature of the tile seems miss-decoded (look at the type of arguments, they seem displaced):
![notgood](https://user-images.githubusercontent.com/1692175/42216501-4d48c916-7ec2-11e8-9836-550ca2bf69f6.png)

I tested it with `vt2geojson` too and the results are the same (maybe the use the same decoder behind the scenes?).

**Comment by Algunenano** [comment]
> After a quick check, that tile doesn't work out of the box with CARTO VL, there is no error anywhere, but nothing (apart from the basemap) is shown. After some debugging I saw that this happens because all the points are outside the tile boundary (buffersize?), and we were clipping them. After disabling clipping the points are shown, and by debugging something more I think that it could work fine:

Yeah, sorry about that. I've just checked and all the points fall into the buffer zone (I'm using 64 to match Mapnik's default).

> However, the last feature of the tile seems miss-decoded (look at the type of arguments, they seem displaced):

I see that now, and it doesn't appear to be exclusive of the last feature. The first N are ok, but the other half isn't. My guess is that the half processed in the parent process are ok and the ones processed in the children (in this case it was 1 child only) aren't encoded properly:
```
      {
        "type": 1,
        "properties": {
          "cartodb_id": 475546,
          "tree_id": "41 MAPLE AVENUE",
          "block_id": 40.64305081,
          "created_at": -74.09335601,
          "tree_dbh": 45,
          "stump_diam": 40.63942116,
          "curb_loc": -74.11247676,
          "status": 953034.020754,
          "health": 172254.78743,
```

This is definitely a must fix bug then. Thanks for the help!

**Comment by Algunenano** [comment]
Tried again with another parallel run and it's affected too: [a4.mvt.zip](https://github.com/CartoDB/postgis/files/2159054/a4.mvt.zip)
```json
        "type": 1,
        "properties": {
          "cartodb_id": 170136.064633,
          "tree_id": 159181,
          "block_id": 323344,
          "created_at": 952533.430547,
          "tree_dbh": 40.64000767,
          "stump_diam": 404375,
          "curb_loc": "571 CASTLETON AVENUE",
          "status": 40.63455082,
          "health": -74.10159378,
          "spc_latin": 962839.90731,
          "spc_common": 171782.479648,
          "steward": 181403,
          "guards": 369671,
          "sidewalk": 182745,
          "user_type": 169281.671001,
          "problems": 369671,
          "root_stone": 955713.487836,
          "root_grate": 955713.487836,
          "root_other": 955713.487836,
          "trnk_wire": 955713.487836,
```

And in comparison, a non broken one:
```json
      {
        "type": 1,
        "properties": {
          "cartodb_id": 122595,
          "tree_id": 329847,
          "block_id": 403226,
          "created_at": "10/15/2015",
          "tree_dbh": 3,
          "stump_diam": 0,
          "curb_loc": "OnCurb",
          "status": "Alive",
          "health": "Good",
          "spc_latin": "Tilia cordata",
          "spc_common": "littleleaf linden",
          "steward": "None",
          "guards": "None",
          "sidewalk": "NoDamage",
          "user_type": "NYC Parks Staff",
          "problems": "None",
          "root_stone": "No",
          "root_grate": "No",
          "root_other": "No",
          "trnk_wire": "No",
          "trnk_light": "No",
          "trnk_other": "No",
          "brnch_ligh": "No",
          "brnch_shoe": "No",
          "brnch_othe": "No",
          "address": "180 MARKET STREET",
```

**Comment by Algunenano** [comment]
Should be fixed with https://github.com/postgis/postgis/pull/263 (one-liner fix)

**Comment by Algunenano** [comment]
Fixed in trunk. Pending backporting the patch here.
